### ISSUE TITLE
cannot update

### ISSUE THREAD

**Issue by rsshel** [lexicalunit/atom-notes#19]
upgraded to high sierra on mac.  cannot update atom-notes
[atomnotesfail.txt](https://github.com/lexicalunit/atom-notes/files/1341064/atomnotesfail.txt)

**Comment by lexicalunit** [comment]
This is probably only happening for `atom-notes` because we have a dependency on `git+https://github.com/lexicalunit/atom-select-list.git#lexicalunit/autocomplete`, whereas most packages strictly only have dependences on published libraries. Sadly there are vital pending updates to [`atom-select-list`](https://github.com/atom/atom-select-list) that `atom-notes` needs to operate correctly. My plan was to wait for those updates to be merged and then update our dependencies accordingly. However the development of `atom-select-list` has been slow. Perhaps it's time I just publish my own version of the library, as frustrating as that would be.

If you've updated your macOS, you will probably need to re-install and/or update xcode, accept its license, and verify the command line tools are installed. See https://apple.stackexchange.com/questions/254380/macos-sierra-invalid-active-developer-path for details. Alternatively you can install `git` yourself instead of relying on the version that comes packaged with xcode. This is what I do, using [Homebrew](http://brew.sh/). If you have Homebrew you can install git with `brew install git`.

**Comment by rsshel** [comment]
Hi,

Thanks for the quick response. Yes, I realized after I posted the issue that my github package was also failing to update.  I reinstalled xcode and everything now works.  Thanks again!  Great package.
