### ISSUE TITLE
Interlinking not working with language-markdown enabled

### ISSUE THREAD

**Issue by memeplex** [lexicalunit/atom-notes#44]
When I install and enable the language-markdown package, the interlinking command stops working, that is it doesn't open the target note at all. After disabling language-markdown and restarting atom, interlinking resumes working. Since language-markdown is a popular package, this is not a minor incompatibility issue.

Versions:
* language-markdown 0.25.1
* atom-notes 1.19.1

**Comment by memeplex** [comment]
The problem seems to be that `[[` and `]]` are not part of the token.

**Comment by lexicalunit** [comment]
I think the reason is that `language-markdown` hardcodes the grammar that it supports, which is exactly one grammar: https://github.com/burodepeper/language-markdown/blob/master/lib/main.js#L82

Many similar packages support a small set of grammars and [some of those even make that set configurable](https://github.com/atom/markdown-preview/blob/master/package.json#L46) in the package settings. If `language-markdown` did this, then it would work with `atom-notes` without any additional work.

My policy in cases like this is to open an issue or PR against the to add support for package interoperability by making the supported grammars configurable.

In the meantime, you can manually change your grammar in Atom between "Atom Notes" and "Markdown". While in the "Atom Notes" grammar interlinks will work just fine, but you may lose many of the features provided by `language-markdown`.

Atom Notes also works just fine with the default Atom Markdown package, `language-gfm`.

**Comment by lexicalunit** [comment]
Actually, this is the reverse problem. Fixing, one sec...

**Comment by lexicalunit** [comment]
Ohhh... I see. This is a novel interaction between `atom-notes` and another package. What I said above still applies and is necessary, but it's not sufficient. `language-atom-notes` wants to parse notes using its grammar, and `language-markdown` of course wants to use its own.

I'm not sure how to resolve this...

**Comment by memeplex** [comment]
Is it absolutely necessary to have language-atom-notes installed? Interlinking works fine with language-gfm without the language-atom-notes package.

**Comment by memeplex** [comment]
Why don't you just strip the `[[` and `]]` in case they were there and, if it turns out you can recover a note file from the remaining, just assume it's a correct interlinking request, instead of letting `found` depend on `[[` and `]]` being there or not, so as to be more grammar agnostic I mean.

**Comment by memeplex** [comment]
Yep, I think it's a more KISS approach, but although I know language-markdown grammar understands wikilinks I'm not sure about language-gfm in this respect. I mean, if you don't provide your own grammar anymore, would people using language-gfm have nicely formatted wikilinks? (it's not my case tough)

If not, I would say that you keep your grammar as a fallback for modes not already supporting wikilink syntax but to make it optional and, yes, totally agree with the 

> Then you could just look in the text buffer at the cursor position for [[whatever]] and treat it as an interlink, no matter what.

part. That is, looking at raw text instead of grammar tokens.

**Comment by lexicalunit** [comment]
Sorry there hasn't been any movement on this lately, I promise I'll be getting back to it soon. Been getting up to speed at a new job and moved across the country 😄

**Comment by lexicalunit** [comment]
@memeplex finally got around to this. Please give v1.19.6 a try, I think it should do the trick.

**Comment by memeplex** [comment]
Great, thanks a lot!
