### ISSUE TITLE
Recognise existing markdown notes - Feature request

### ISSUE THREAD

**Issue by tgrrr** [lexicalunit/atom-notes#52]
Great program, kudos.

I've been keeping notes by writing markdown files. And I've set the archive folder for notes to that folder. Is there a way to search for and recognise existing notes in that folder (and subfolders)?

**Comment by lexicalunit** [comment]
Thanks! The plugin should pick up existing notes and notes in subfolders automatically, yes. As long as you point Atom Notes at the directory you want to use for notes, it will index that directory and all Markdown files in it at start up. If you have a lot of files it may take a couple seconds for it to finish.

**Comment by tgrrr** [comment]
In my case it's only reading the original notes. I can successfully create a new note, so the directory is correct, and so are the permissions. Any suggestions?

**Comment by lexicalunit** [comment]
🤔 maybe somehow it's loading the cache, and the cache only includes the new files. You could try moving all the files out of the folder, then moving them back in. That would trigger a "new file" event when they are moved back in for every single file.

Maybe also create a backup of the entire directory first, just in case something goes wrong in the moving around of your files. I just want to be sure you don't lose your files! It should be safe, but just to be sure absolutely sure it never hurts to do a backup.

**Comment by tgrrr** [comment]
I've actually tried that

**Comment by lexicalunit** [comment]
Make sure you try it while Atom is running so that the plugin can be live to catch the new file events as they happen.

That's the only thing I can think of that could be happening. The plugin does have a cache so it starts up quickly and doesn't have to re-index files every single time it starts up. But the plugin doesn't have any way to differentiate an old file from a new file, they're all just files...

You can actually pull up the chromium developer tools window in Atom (shortcut is `command + option + i` on macOS) to see some runtime information from `atom-notes` in your log. You may see things like:

```
atom-notes: loading...
atom-notes: ready in 1327ms
```

When you see that `loading...` message that means it's using the cache. If you see `indexing...` instead that means it is re-indexing your entire notes directory and it will absolutely index every single file in that directory. So long as the files you want it to index have the right file extensions, of course.

One way to trigger the `indexing...` is to manually clear your caches. You can also do this from the developer tools console by executing:

```
atom.deserializers.clear()
```

Then from Atom Settings you can disable and then re-enable the `atom-notes` plugin. If you've done everything right you'll see something like this in the logs:

```
No deserializer found for {deserializer: "SearchIndex", [...]}
atom-notes: indexing...
atom-notes: ready in 532ms
```

🤔Actually... one other possibility just entered my mind. Can you check that the old files have extensions in lowercase? By default `atom-notes` only looks for files with the following extensions: `'.md', '.markdown', '.adoc', '.txt'`. That's actually case sensitive now that I'm looking at my source code. Come to think of it that's a bug. The plugin should be able to handle mixed-case file extensions gracefully. I'm curious now if maybe this is what's causing you problems.

**Comment by LucianoAzzigotti** [comment]
> Thanks! The plugin should pick up existing notes and notes in subfolders automatically, yes. As long as you point Atom Notes at the directory you want to use for notes, it will index that directory and all Markdown files in it at start up. If you have a lot of files it may take a couple seconds for it to finish.

sorry, simple question, how can I customize the notebook folder in order, for example to put some notebook notes inside a dropbox folder? thanks!

**Comment by lexicalunit** [comment]
@LucianoAzzigotti `atom-notes` should naturally handle recursive subdirectories. For example I have my notes broken into directories by project name. When creating a note simply type in the directory structure you want as the prefix for the note. For example I could create a new note by searching for the text `"Project1/Something"` -- when no note is found I would press enter to create a new note. The note would be stored in the file `/path/to/my/notes/directory/Project1/Something.md`.

I also set my notes directory to be a subdirectory of my Dropbox folder in the plugin settings, so that Dropbox will sync my notes for me.

**Comment by tgrrr** [comment]
Dropbox can break git @lexicalunit

**Comment by lexicalunit** [comment]
Yeah, I would definitely avoid creating git repositories in the notes directory. I'm not sure what the use case for that would be though.
