### ISSUE TITLE
Can't use markdow preview

### ISSUE THREAD

**Issue by webdev-skynet** [lexicalunit/atom-notes#8]
when I have a note opened and I try to preview it using the default Markdown preview package nothing happens. I try using the command palette and also from the package menu but both doesn't work for some reason, ass soon as I try on a normal .md that is not bind to atom-notes it works.

**Comment by lexicalunit** [comment]
The `markdown-preview` package has a configuration for the kinds of files it supports. I have code in `atom-notes` to try and detect when `markdown-preview` is an activated package so that I can modify its default settings to include our Atom Notes grammar. Seems like that isn't working in your case :(

Fortunately there's a workaround. You can manually edit your settings for `markdown-preview` to add the Atom Notes grammar.

Open your Settings View &mdash; <kbd>Cmd + ,</kbd> on macOS and <kbd>Ctrl + ,</kbd> on Linux/Windows) &mdash; then click on the **Packages** tab. Find the settings for `markdown-preview`. There will be a setting for the list of supported grammars. For example, the default list is:

```
source.gfm, source.litcoffee, text.html.basic, text.md, text.plain, text.plain.null-grammar
```

To get previews working for Atom Notes, you need to ensure that you've added `source.gfm.notes` to that comma separated list.

**Comment by webdev-skynet** [comment]
thank you very much! I will try this

**Comment by lakonis** [comment]
However, the grammar setting for markdown-preview used to be available from its settings pages. Not anymore. To edit the grammars, open `~/.atom/packages/markdown-writer/lib/config.coffee` and add `source.gfm.notes` in the `defaults["grammars"]` parameter.

**Comment by lexicalunit** [comment]
Grammars should still be a valid configuration setting for `markdown-preview`, [based on its latest source code](https://github.com/atom/markdown-preview/blob/master/package.json#L42).

If it's not showing up for you in the UI, that's probably a [`settings-view`](https://github.com/atom/settings-view) bug.

And rather than editing the source code of `markdown-preview`, you can just edit your `config.cson` directly:

```cson
"*":
  [...]
  "markdown-preview":
    grammars: [
      "source.gfm"
      "source.litcoffee"
      "text.html.basic"
      "text.md"
      "text.plain"
      "text.plain.null-grammar"
      "source.gfm.notes"
    ]
  [...]
```

**Comment by lakonis** [comment]
Yes, `markdon-writer` indeed, which does have grammars configuration setting, although it doesn't show up in the UI. For me at least.
However, thanks for the advice on editing `config.cson`.
